### ISSUE TITLE
Camera problem bug

### ISSUE THREAD

**Issue by umtulnefsi** [MASVA/MA-XML-8.0-CROATIAN#2]
Hello. I want to report a single error on miui 8.1.2.0 and earlier versions miui 8, which occurs only in the Croatian language. This error does not exist when I switch to English. This is a camera, when the camera settings to choose the picture there is a date and time. Then appears the mistake of camera connect error and the picture is not saved anywhere, can not take pictures. When you turn off the option that is not in the picture is the date and time it's all good, or when I was in English, but as soon as I was in the Croatian language and with this turn on option appears to me that error. I would be very grateful if this error was corrected. Please note that earlier this mistake was in English, but I see that it is now only in Croatian. Greeting.

**Comment by MASVA** [comment]
yes, this is known problem that we can not solve yet
the same problem is on the global dev ROM  which uses the same translation and the bug has been reported to xiaomi
which phone you have?
on some devices , which are on the xiaomi.eu ROM does not have these problems
eg mi2s 6.12.1

**Comment by umtulnefsi** [comment]
This problem does not exist on any ROM of global stable version, while the china stable there. I informed developers who work on china stable but not solve this problem by first miui 8 versions



On Sun, Dec 4, 2016 at 6:37 PM +0100, "MASVA" <notifications@github.com<mailto:notifications@github.com>> wrote:


yes, this is known problem that we can not solve yet
the same problem is on the global dev ROM which uses the same translation and the bug has been reported to xiaomi
which phone you have?
on some devices , which are on the xiaomi.eu ROM does not have these problems
eg mi2s 6.12.1

-

**Comment by umtulnefsi** [comment]
I have redmi 3S device 16 gb marshmalow 6.0.1



On Sun, Dec 4, 2016 at 6:37 PM +0100, "MASVA" <notifications@github.com<mailto:notifications@github.com>> wrote:


yes, this is known problem that we can not solve yet
the same problem is on the global dev ROM which uses the same translation and the bug has been reported to xiaomi
which phone you have?
on some devices , which are on the xiaomi.eu ROM does not have these problems
eg mi2s 6.12.1

-

**Comment by MASVA** [comment]
there is no hr language in china stable/global stable
global dev has

**Comment by umtulnefsi** [comment]
Yes that is true.
I use eu rom 8.1.2.0, which is made of china stable versions. At eu rom there is Croatian. My device is redmi 3S, miui 8.1.2.0 by xiaomi.eu



On Sun, Dec 4, 2016 at 6:42 PM +0100, "MASVA" <notifications@github.com<mailto:notifications@github.com>> wrote:


there is no hr language in china stable/global stable
global dev has

-

**Comment by MASVA** [comment]
i drugi put prijavi slobodno pogrešku na hr jeziku
ionako ga obojica koristimo
lp

**Comment by umtulnefsi** [comment]
Ok, sada stvarno nema ni jedne greske osim te na kameri kada ukkjucim opciju da stoji datum i vrijeme na slici.
Je li to do china stable roma ili je striktno do eu roma. Pozz



On Sun, Dec 4, 2016 at 6:47 PM +0100, "MASVA" <notifications@github.com<mailto:notifications@github.com>> wrote:


i drugi put prijavi slobodno pogrešku na hr jeziku
ionako ga obojica koristimo
lp

-

**Comment by MASVA** [comment]
nema to veze sa china romom
naš rom je baziran na njemu
negdje je greška u prijevodu, neka varijabla ili nešto drugo
nešto sam tražio i ispravljao, i kako sam rekao, na nekim uređajima je ok, na nekima ne
sad čekam da xiaomi dev pogledaju dal će pronaći gdje je problem
bug je prijavljen i log greške je poslan, sad nam samo ostaje čekati hoće li i kada to pogledati/riješiti

**Comment by umtulnefsi** [comment]
Svaka čast. Drago mi je da je to poslano, da mogu očekivati kad tad da ce to biti popravljeno. I da eto bas da upitam zasto je eu rom baziran na china romu, zasto nije na global stable jer je global pouzdaniji po mon iskustvu. Ja kad flesujem uredjaj na global stable zadnju verziju, kamera radi sve ok. Razumijem sta mi zelite reci s tom varijablom kodova i slicno. Hvala puno.



On Sun, Dec 4, 2016 at 6:56 PM +0100, "MASVA" <notifications@github.com<mailto:notifications@github.com>> wrote:


nema to veze sa china romom
naš rom je baziran na njemu
negdje je greška u prijevodu, neka varijabla ili nešto drugo
nešto sam tražio i ispravljao, i kako sam rekao, na nekim uređajima je ok, na nekima ne
sad čekam da xiaomi dev pogledaju dal će pronaći gdje je problem
bug je prijavljen i log greške je poslan, sad nam samo ostaje čekati hoće li i kada to pogledati/riješiti

-

**Comment by MASVA** [comment]
a vidiš,mi smo drugog mišljenja
nama je china dev bolji od stable i zato njega koristimo

**Comment by umtulnefsi** [comment]
China radi brze update, ali sa ovom kamerom global je to rijesio jos u 8.0.3.0 verziji cini mi se, a china jos nisu, ali vjerujem da hoce, bio bi red, hehe
I svaka vam pohvala za eu rom, sve moje kolege zele da im flesujem uredjaje na eu rom jer je UI interface puno ljepsi na eu romu. Ikone su vam prefine, od facebooka, vibera whats app, dropbox i sl. Nemojte ih mijenjati jer su stvarno lijepe, slicne kao na iOS u ali opet ljepse po meni. Puno podrska za vas posao.



On Sun, Dec 4, 2016 at 7:02 PM +0100, "MASVA" <notifications@github.com<mailto:notifications@github.com>> wrote:


a vidiš,mi smo drugog mišljenja
nama je china dev bolji od stable i zato njega koristimo

-

**Comment by MASVA** [comment]
neće china rom nikad imati eu jezike
zato su dali van global
thx za pohvale

**Comment by umtulnefsi** [comment]
Samo neka opstane eu rom. Jedino sto ce global mozda nekad dobiti hrvatski jezik, mozda, a mozda se i varam
Ali svejedno i da dobije hrvatski, opet je eu rom meni puno bolji i ljepsi izgledom i jos plus na eu romu mi se svidja sto ne dolazi ni jedna instalirana aplikacija, nego samo ona koju ja zelim. Lijep pozdrav i hvala za sve.



On Sun, Dec 4, 2016 at 7:09 PM +0100, "MASVA" <notifications@github.com<mailto:notifications@github.com>> wrote:


neće china rom nikad imati eu jezike
zato su dali van global
thx za pohvale

-

**Comment by MASVA** [comment]
global dev ima hr
još čekam da ga stave u global stable
lp
zatvaram

**Comment by umtulnefsi** [comment]
Da, tacno beta verzija ima hr na globalu. Sad kad ce doci na stable ostaje, al ponavljam opet prethodnu poruku, hehe



On Sun, Dec 4, 2016 at 7:14 PM +0100, "MASVA" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2<https://github.com/MASVA/MA-XML-8.0-CROATIAN/issues/2>.

-

**Comment by umtulnefsi** [comment]
Evo jedan sitni sitni propust kod prijevoda. Rijec OSJECAJ, slovo J na kraju je kao eksponent, to je vjerovatno zbog engleskog ®
Real feel®
pozz.



On Sun, Dec 4, 2016 at 7:14 PM +0100, "MASVA" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2<https://github.com/MASVA/MA-XML-8.0-CROATIAN/issues/2>.

**Comment by MASVA** [comment]
Riješeno
Stvar. osjećaj bude sada, vjerojatno string ima ograničen broj kao što si i naveo
Lp

**Comment by umtulnefsi** [comment]
Ja sam dosadan al evo jos malo uocene greskice. U kalkulatoru. Saljem screenshot.



On Tue, Dec 6, 2016 at 6:42 PM +0100, "MASVA" <notifications@github.com<mailto:notifications@github.com>> wrote:


Riješeno
Stvar. osjećaj bude sada, vjerojatno string ima ograničen broj kao što si i naveo
Lp

-

**Comment by umtulnefsi** [comment]
Još jedna stvar koja bi se mogla ispraviti. Saljem screenshoot. I u aplikaciji vrijeme ono gsje pise stvar.osjecaj. Opet je slovo J u vrhu rijeci na kraju, drugacije od ostalih.



On Tue, Dec 6, 2016 at 6:42 PM +0100, "MASVA" <notifications@github.com<mailto:notifications@github.com>> wrote:


Riješeno
Stvar. osjećaj bude sada, vjerojatno string ima ograničen broj kao što si i naveo
Lp

-
