### ISSUE TITLE
Battery drain Xiaomi Redmi PRO 64GB

### ISSUE THREAD

**Issue by reny-mapich** [MASVA/MA-XML-8.0-CROATIAN#3]
Hello I have been expiriencing a battery drain bug. I have solved a camera bug deleting files form camera settings. But battery drain is unacceptable. I'm having 1,5h screen on time, this is too shame for a battery of this capacity. I have already tried installation of those 2 zip files from forum but obviously with no success.

**Comment by MASVA** [comment]
hi
what files you deleted ?
which ROM?

**Comment by reny-mapich** [comment]
I have press the left key to see Open apps, scroll down on camera and went to camera settings of camera app and just press delete files this fixed unable to start issue.
My ROM is MIUI EU 8.0 stable 8.0.6.0 (MHQCNDG)
